app:
  port: 4000
  global_prefix: 'api'

database:
  sync: true
  postgres:
    type: 'postgres'
    host: 'localhost'
    port: 5432
    user: 'postgres'
    password: 'postgres'
    database: 'project'